stages:
  - build

build_server:
  stage: build
  image: node:20
  before_script:
    - node -v
    - npm -v
    - npm install -g npm@11.9.0
    - npm -v
    - cd server
    - npm ci
  script:
    - npm run build

build_client:
  stage: build
  image: node:20
  before_script:
    - node -v
    - npm -v
    - npm install -g npm@11.9.0
    - npm -v
    - cd client
    - npm ci
  script:
    - npm run build
